force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Money__c.field-meta.xml
<CustomField>
    <fullName>Money__c</fullName>
    <label>Money</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Сash receipts</fullName>
            </value>
            <value>
                <fullName>Writing off money</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransactionTriggerHelper.cls
public class TransactionTriggerHelper {
    
    public static void checkNewTransaction(List<Transaction__c> newTransactions) {
        if(newTransactions != null) {
            Double totalAmountOfMoney = 0;
            String userId = UserInfo.getUserId();
	        User currentUser = Database.query('SELECT Id, Name, Balance__c FROM User WHERE Id =: userId LIMIT 1');
            for(Transaction__c tr : newTransactions) {
                if(tr.Operation__c == 'Writing off money' && totalAmountOfMoney < currentUser.Balance__c && currentUser.Balance__c >= 0) {
                    totalAmountOfMoney += tr.Money__c;
                    currentUser.Balance__c -= tr.Money__c;
                } else if(tr.Operation__c == 'Сash receipts') {
                    currentUser.Balance__c += tr.Money__c;
                }
                if(totalAmountOfMoney > currentUser.Balance__c) {
	                tr.addError('Not enough money!');
                }
            }
            update currentUser;
        }
    }
    
    public static void checkUpdateTransaction(List<Transaction__c> newTransactions, List<Transaction__c> oldTransactions) {
        if(newTransactions != null) {
            String userId = UserInfo.getUserId();
	        User currentUser = Database.query('SELECT Id, Name, Balance__c FROM User WHERE Id =: userId LIMIT 1');
            for(Transaction__c newTr : newTransactions) {
                for(Transaction__c oldTr : oldTransactions) {
                    currentUser.Balance__c += oldTr.Money__c - newTr.Money__c;
                }
            }
            update currentUser;
        }
    }
}