force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Money__c.field-meta.xml
<CustomField>
    <fullName>Money__c</fullName>
    <label>Money</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Сash receipts</fullName>
            </value>
            <value>
                <fullName>Writing off money</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransactionsController.cls
public class TransactionsController {
    
    @AuraEnabled
    public static UserWrapper getData() {
        String userId = UserInfo.getUserId();
        User currentUser = Database.query('SELECT Id, Name, Email, Address, Phone FROM User WHERE Id =: userId LIMIT 1');
        List<Transaction__c> transactionsList = Database.query('SELECT Id, Name, Transaction_Date__c, Money__c, Operation__c ' + 
                                                               'FROM Transaction__c ' + 
                                                               'WHERE User__r.Id =: userId ' + 
                                                               'ORDER BY Transaction_Date__c DESC');
		UserWrapper wrapper = new UserWrapper(currentUser, transactionsList);
        return wrapper;
    }
    
    @AuraEnabled
    public static UserWrapper deleteRecordFromTable(Id idRecordToDelete) {
        Transaction__c transactionToDelete = [SELECT Id
                                              FROM Transaction__c
                                              WHERE Id =: idRecordToDelete
                                              LIMIT 1];
        delete transactionToDelete;
        return getData();
    }
    
    public class UserWrapper {
		@AuraEnabled
        public id userId;
		@AuraEnabled
        public String userName;
		@AuraEnabled
        public String userEmail;
		@AuraEnabled
        public String userAdress;
		@AuraEnabled
        public String userMobile;
		@AuraEnabled
        public List<Transaction__c> userTransactions;
        
        public UserWrapper(User currentUser, List<Transaction__c> transactionsList) {
            this.userId = currentUser.Id;
            this.userName = currentUser.Name;
            this.userEmail = currentUser.Email;
            this.userAdress = currentUser.Address.getCity();
            this.userMobile = currentUser.Phone;
            this.userTransactions = transactionsList;
        }
    }
}