force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Money__c.field-meta.xml
<CustomField>
    <fullName>Money__c</fullName>
    <label>Money</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Сash receipts</fullName>
            </value>
            <value>
                <fullName>Writing off money</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransactionsControllerTest.cls
@isTest
public class TransactionsControllerTest {
    
    @testSetup
    public static void setup() {
        Transaction__c testTransaction1 = new Transaction__c();
        testTransaction1.Name = 'Test1';
        testTransaction1.Transaction_Date__c = System.today();
        testTransaction1.Money__c = 10;
		testTransaction1.Operation__c = 'Сash receipts';
        testTransaction1.User__r = [SELECT Id, Name FROM User WHERE Name = 'Vladik Leshko' LIMIT 1];
        insert testTransaction1;

        Transaction__c testTransaction2 = new Transaction__c();
        testTransaction2.Name = 'Test2';
        testTransaction2.Transaction_Date__c = System.today();
        testTransaction2.Money__c = 10;
		testTransaction2.Operation__c = 'Сash receipts';
        testTransaction2.User__r = [SELECT Id, Name FROM User WHERE Name = 'Integration User' LIMIT 1];
        insert testTransaction2;
    }
    
    @isTest
    public static void testGetData() {
        User testUser1 = [SELECT Id, Name, Email, Address, Phone FROM User WHERE Name = 'Vladik Leshko']; 
        User testUser2 = [SELECT Id, Name, Email, Address, Phone FROM User WHERE Name = 'Integration User'];
        List<Transaction__c> testTransactionsList = [SELECT Id, Name, Transaction_Date__c, Money__c, Operation__c, User__c 
                                                     FROM Transaction__c];
        System.runAs(testUser1) {
	        TransactionsController.UserWrapper wrapper = new TransactionsController.UserWrapper(testUser1, testTransactionsList);
			wrapper = TransactionsController.getData();
            System.assertEquals('Vladik Leshko', wrapper.userName);
        }
        System.runAs(testUser2) {
	        TransactionsController.UserWrapper wrapper = new TransactionsController.UserWrapper(testUser2, testTransactionsList);
			wrapper = TransactionsController.getData();
            System.assertEquals('Integration User', wrapper.userName);
        }
    }
    
    @isTest
    public static void testDeleteRecord() {
        List<Transaction__c> testTransactionsList = [SELECT Id, Name, Transaction_Date__c, Money__c, Operation__c, User__c 
                                                     FROM Transaction__c];
        System.assertEquals(2, testTransactionsList.size());
		TransactionsController.deleteRecordFromTable(testTransactionsList[0].Id);
        testTransactionsList = [SELECT Id, Name, Transaction_Date__c, Money__c, Operation__c, User__c 
                                FROM Transaction__c];
        System.assertEquals(1, testTransactionsList.size());
    }
    
}